### ISSUE TITLE
General insight into architecture and reasoning

### ISSUE THREAD

**Issue by joscha80** [akellai/rfid-music#1]
Dear akellai,
I am quite new to working/ playing with MCUs and actually trying to create a similar "remote control" for my daughter. I came across your impressive project later on through the power savings discussion thread.
I initially chose my setup quite different, I am using 
 Node MCU V2 (ESP 8226) and MFRC522 and connected these directly. I use micropython for the programming as I am more familiar with it. 
I then read cards and currently use IFTTT service via webhooks to trigger the start of favorites (not very elegant, but it seemed very straightforward). I am stuck now on the deepsleep and how to wake the ESP as I would like to use a battery / powerbank powered solution.

Now to my question: could you explain a bit why you choose the hardware setup like you did, what role each part plays and how you manage to wake the ESP from Deepsleep when a card is present at the reader? I know  ... beginner questions, but I would really appreciate if you could share a bit more insight.

**Comment by akellai** [comment]
the high-level architecture/idea is as follows:
MCU connected to the MFRC522 needs to be in the deep sleep most of the time. It would wake up itself periodically (e.g. once every second), wake up the MFR and quickly check if there is anything inserted in the reader. If a card is detected, the MSU will do its work: read the card ID, wake up another MCU (e,g, MSP) to send the data out etc. The whole detection cycle should take small fraction of a second to minimize the power consumption.
I don’t believe using ESP 8226 will work as wake up for it takes approximately 300 msec – comparable with the 1 second sleep interval. That means you will not be able to realize any significant power saving with such a config.

**Comment by joscha80** [comment]
Thanks, that actually helped a lot. At first I hoped that i can use some sort of signal directly by MFRC522 to wake up the ESP, but this seems not to be a function that the MFRC provides. Your explanations helped a lot. I will build the first prototype for connection to a power supply and then add on a battery version later on.
